[workspace]
members = ["crates/nixtui"]

[package]
name = "nixtui-core"
version = "0.1.0"
edition = "2021"

[[example]]
name = "selector"
path = "examples/selector.rs"


[dependencies]
nix = { version = "0.29.0", features = ["ioctl", "term"] }
terminfo = "0.9.0"
thiserror = "2.0.11"
